replicaCount: 1

image:
  repository: 696155685144.dkr.ecr.us-east-1.amazonaws.com/sevflow-app
  tag: "image pull error"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

env:
  appEnv: dev
  appVersion: "1.0.0"

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: ""
  path: /
  pathType: Prefix
  tls: []

resources: {}

monitoring:
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics
    labels:
      release: kube-prom-stack

ingress-nginx:
  enabled: false
  controller:
    service:
      type: LoadBalancer

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

progressiveDelivery:
  enabled: false
  strategy: canary
  canary:
    stableServiceSuffix: stable
    canaryServiceSuffix: canary
    steps:
      - setWeight: 20
      - pause:
          duration: 2m
      - setWeight: 50
      - pause:
          duration: 5m
  blueGreen:
    activeServiceSuffix: active
    previewServiceSuffix: preview
    autoPromotionEnabled: false
    previewIngress:
      enabled: false
      className: nginx
      annotations: {}
      host: ""
      path: /
      pathType: Prefix
      tls: []
  analysis:
    enabled: false
    prometheus:
      address: http://kube-prom-stack-prometheus.monitoring.svc.cluster.local:9090
    errorRate:
      interval: 1m
      range: 2m
      threshold: 0.05
      failureLimit: 3
