image:
  repository: "696155685144.dkr.ecr.us-east-1.amazonaws.com/sevflow-app"
  tag: "be6a4df1a53741d09727c0b0ed18b7bea2095ce5"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  appEnv: prod
  appVersion: "1.0.0"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-http
  host: app.sevflow.app
  path: /
  pathType: Prefix
  tls:
    - hosts:
        - app.sevflow.app
      secretName: app-sevflow-app-tls

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
