server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-http
    hosts:
      - prometheus.sevflow.app
    path: /
    pathType: Prefix
    tls:
      - secretName: prometheus-sevflow-app-tls
        hosts:
          - prometheus.sevflow.app

alertmanager:
  enabled: false

pushgateway:
  enabled: false
