configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argo.sevflow.app
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-http
    tls: true
    extraTls:
      - hosts:
          - argo.sevflow.app
        secretName: argo-sevflow-app-tls

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
